### ISSUE TITLE
[Questions] The "clean-arthitecture" definition about the book.

### ISSUE THREAD

**Issue by WindSoilder** [pycabook/pycabook#22]
Very thanks for your book :) I like it very much.  
But there are some questions after reading your book :(
1. Does the "clean-arthitecture" only work for OO-programming?
2. The mainly thing is about the `arthitecture layer`, refer to the book (Session *Main layers, Chapter1, Part2*.  And Session *Use cases, Chapter2, Part2*):
* `Entities` is the inmost layer,
* `Use cases` comes middle,
* `External systems` is outer level to use cases.

And refer to that:
```
A clean architecture is also a spherical architecture, with inner (lower) layers completely encompassed by outer (higher) ones, and the former ones being oblivious of the existence of the latter ones.
```
According to P85, which says:
```
The repository is our storage component, and according to the clean architecture it will be implemented in an outer level (external systems). 
```
But the last paragraph of P84 says:
```
Use cases are the places where this happens, and they might or might not be directly linked to the external API of the system.
```

I think that `User case` level don't know the existence of `External systems`(because `External systems` is outer level), but why `Use case` can invoke interface which is exposed by `External systems`?

**Comment by lgiordani** [comment]
Hi, and thanks for the message!
Your questions are very interesting and I am considering writing something longer to answer them than a comment here, but however, I'll give you at least an initial answer.

1. No, the clean architecture is an architectural pattern, thus is is concerned with components and relationships between components. Actually, since layers are decoupled and communicate through APIs you can potentially implement them in different languages and/or paradigms. This is obviously easier for external systems, but it is possible for internal layers as well. Obviously you will have the problem of linking different languages (i.e. calling a language from another), but this is something we do very often in other cases as well, for example when we implement something in C to leverage the speed and optimisation of the language, but then call it from Python.

2. Pay attention to the meaning of "knowing" here. It means that a layer is not aware of the internals of another layer, and cannot deal with it other than through a well-established API. Practically speaking, every actor in any layer can access entities, they are well known, and the layer actually knows *how* they are implemented, for example that there is a `.name` field. This is not true the other way round. An external layer such as the one that implements a storage repository, exposes an API that has to be the same for every other storage layer, and nobody knows how things work internally. Well, of course you know, if they are part of the same project, but you should act as if you didn't know. In the example that you mention, user cases are aware of the existence of something outside, but they don't know *what* this is. For example they don't know the actual class that implements the behaviour, which is what allows us to switch one class with another one that exposes the same API. Decoupling means weakening the dependency on the specific implementation, not disconnecting layers. I hope this is clear enough, let me know if it is still foggy.

**Comment by WindSoilder** [comment]
Very thanks for that!  I fully know what "knowing" actually meaning about :-)

To be honest,  I'm very confuse about when should we make something together to a component.  And how to know which component is too large (like a very-very large class or function), so we should split them out to multi-component.  Sometimes there are too much components :-(

But I believe that there is no general rule to smell that.  It's base on our experience and the actual projects.  Am I right?

**Comment by lgiordani** [comment]
Yes, there is no rule set in stone. Generally speaking I try not to overengineer things (as I'm prone to do it), let me give you a simple example from my daily work. When should you isolate functions in a library? 

Well, I am working in infrastructure these days, so I write many bash and Python scripts to manage instances, containers, load balancers, and so on. When I need a new script I usually write everythin in the same file, sometimes I define functions on the spot, or give my variables stupid random names. I'm very strict about names, so when I cannot come up with a proper name immediately I just avoid wasting 10 minutes trying to figure out a good name. Let's call it `list_results` or `this_is_it`.

While I do this, I refactor my code (in infrastructure unfortunately TDD is a luxury, sometimes, but I believe you recognise the pattern). When I see that a local function works I move it at the top of the script, trying to decouple it from local variables, and testing it. If the function is generic enough (like a filter for a list of dictionaries based on regular expressions, that probably useful in other scripts), I'll move it to a common file, otherwise I'll leave the function in the script. When I develop another script and I realise that I will solve a problem I already solved, I usually go and see if I can abstract the functions written for a previous script, and possibly move them to a common file, or to a library, if I realise that I need to install the code in other environments.

So, when do you have to isolate things in a component? Usually when you think this would make them easier to maintain, allow other parts of the system to avoid reinventing the wheel, relax the complexity of the part of the code you are working on.

You mention the risk of having too many components. Yes, take the example of microkernel operating sytems. Are they better than monolithic ones? It depends. (With this sentence I might have started a terrible flame war a decade ago). You might and up having the code split into so many small components that the system spends 90% of its running time creating and exchanging messages among components, wasting resources. On the other hand you might have an incredibly fast monolithic system that cannot cope with changes, or that uses up the whole system memory because it cannot discard unused parts of the code.

So, yeah. It's mostly a matter of experience. There are patterns and good practices, however, so look for books about design if you are interested in these topics; for me, the classical Design Patterns was a game changer, in terms of mindset. Another book I loved and helped me a lot is Enterprise Integration Patterns. It's about messaging solutions, but it is well written, and the topic is not far from the components/layers problem that we are discussing here.

**Comment by WindSoilder** [comment]
Yeah, very thanks for your answer.  And I think I can close this issue.
