### ISSUE TITLE
[Questions] Domain models: Objects, data classes, or data structures?

### ISSUE THREAD

**Issue by faustgertz** [pycabook/pycabook#24]
[Uncle Bob says](https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html):

> Entities encapsulate *Enterprise wide* business rules. An entity can be an object with methods, or it can be a set of data structures and functions. It doesn’t matter so long as the entities could be used by many different applications in the enterprise.

In _Clean Code_, Uncle Bob elaborates on the distinction:

>  Objects hide their data behind abstractions and expose functions that operate on that data. Data structures expose their data and have no meaningful functions.

I don't see any *business rules* in your rentomatic domain model. It is not only you. I don't see them in other clean architecture tutorial domain entities either. The entities don't seem to have methods or, as Sandi Metz might say, messages that go between them. They are data structures wrapped up as objects.

This may be due to the nature of tutorials. Entities found in tutorials may not resemble entities found in actual applications. So, in your experience, are entities usually objects or data structures? Which methods or functions usually go with actual domain entities?

Also, on page 76 under **Entities** you say:

> [These models] don’t contain methods to dump themselves to JSON strings...

Based on that, should our models have `to_dict` and `from_dict` methods? Or is the convenience of these methods ok because they use a Python data structure?  Is the lack of a method dumping to JSON because it is a string sometimes used for presentation? You handle JSON serialization with a serializer for each domain entity.

Finally, I understand why you may not have used data classes in your book. But, if domain entities are data structures, do you think data classes are rich enough for domain models? They seem rich enough for your rentomatic domain model.

```Python
from dataclasses import asdict, dataclass


@dataclass
class Room:
    __slots__ = ['code', 'size', 'price', 'latitude', 'longitude']
    code: str
    size: float
    price: float
    latitude: float
    longitude: float

    @classmethod
    def from_dict(cls, adict):
        return cls(**adict)

    def to_dict(self):
        return asdict(self)
```

I could even drop the `to_dict` and `from_dict` methods. This makes it more like a set of data structures and functions. 

```Python
from dataclasses import asdict


def test_functions_on_dataclass():
    room_dict = {
        'code': uuid.uuid4(),
        'size': 200,
        'price': 10,
        'longitude': -0.09998975,
        'latitude': 51.75436293
    }
    # Method style
    room = r.Room.from_dict(room_dict)
    assert room.to_dict() == room_dict

    # Data class (data structure and functions?) style
    room = r.Room(**room_dict)
    assert asdict(room) == room_dict
```

This is all still new to me. I might be missing a lot. What do you think?

**Comment by soulfulfaust** [comment]
As data classes are user-defined classes with various generated special methods such as __init__() and __repr__() to automatically added to them, they are rich enough for domain models.

**Comment by lgiordani** [comment]
Faust, apologies for the late reply, I completely forgot this.

The nature of Entities and what they should contain is definitely an interesting topic, and as often happens, I believe there is no clear line that can be drawn or "perfect recipe".

Let me first answer the easiest part of your question: yes, I believe dataclasses are a perfect match for the clean architecture, and I am planning to expand the book to include them. At the time of writing dataclasses were still in development and I didn't want to overload the reader with concepts that are new additions to the language. I preferred to stick to the basics of the language to be crystal clear abut the architecture, which is ultimately my goal in the book.

As for the content of entities, the `dict`-related methods are there just because dicts are Python structures. JSON is not a native data type, so I prefer to consider it a translation of the object into something, and thus to have an external agent that performs it. Your feelings might differ, and I wouldn't argue if I found the `to_json` method in your entities. As for business rules, the problem is the same: we isolate them in use cases for convenience. Once isolated, they are shorter and easier to understand, and they can be easily tested. You might as well have them inside objects and everything would work.

Well, almost. After all, you might fit everything in a single big class called `Program()` and everything would work, isn't this what non-OOP languages do? They call "program" the "external class", global variables the attributes of this class, and so on. So, what do you put into entities? Small functions, code that affects the entity only and that is not important or big enough to be called use case. The decision is up to you, and you might discover that at a certain point, what you though was a small function has to evolve and become a proper use case. All in all, the architecture is about "knowing what is where and why", not about doing "the right thing", that is usually very difficult to identify, if not impossible.

I hope this helps, let me know if I was too generic or if I answered your question. This time I'll try to be a bit quicker with my answer :wink:
