### ISSUE TITLE
Second edition, figures slightly cut on the pdf - plus guide for reporting typos

### ISSUE THREAD

**Issue by 1110sillabo** [pycabook/pycabook#40]
Hi @lgiordani! 

Thank you so much for your book and efforts. Conceptually, it was HJP who brought me here after putting me under the supervision of the testing goat and I am really appreciating your book (as well as some of your talks and articles).

I have a kind of "double issue" (sorry for that).

1. In the pdf version I've downloaded from LeanPub the text of the images is sometimes cut. E.g.: In Figure 1 on page 10 instead of "Web framework" I read something closer to "web frameworł" (with the cut "k" resulting in the Polish "ł").
This is happening again with "Storage wrappei" (fig. 5 and 6, page 14) and elsewhere (I can send a more detailed report once I've finished the book).

I doubt the texts in the images were "cut" from the start, so there's probably an issue with LeanPub typesetting the images.

2. What's your policy for reporting typos? Do you prefer a PR per each thing or multiple typos can be grouped? 
(I'm tracking all I'm noticing. Most are typos like "RObert Martin" or some issues with Markua/LeanPub with a ^languages footnote, etc.
Still, some might be more disputable and "stylistic" (e.g.: missing point at the end of the dedication; adding semicolumns before the code samples - kind of an architectual decision for the book). Last but not least, I'm no native speaker.

As the book is free, has cool a repo with the author taking care of it, and is teaching me a lot I feel obliged to point out at least the typos I can spot. But I don't want to bother you too much with typo-related PRs.

Ok, enough of a break - time to go back to your book! :)
Thank you once more!

**Comment by lgiordani** [comment]
Hey thank you very much for the message and your kind words. So, many of the issues come from the new way I used to create the PDF (Asciidoctor), which is not perfect unfortunately. Leanpub's system was good but limited, this less limited but has issues... it's a struggle! :joy_cat:  I haven't noticed the one you mentioned. To be honest I was fed up or proofreading the same text over and over and haven't looked at it since I published it :man_shrugging: 

Anyway, I'll slowly sort them out, I hope. In general, I'm more than happy to receive issues that point out any sort of error, be it a typo or a a stylistic problem. I also appreciate advice on the form of sentences, sometimes I can be convoluted :joy_cat: As for the content and the specific choices I'm open to discuss them (there is always something to learn) but I would prefer to keep them in the repository's discussions page (https://github.com/pycabook/pycabook/discussions) as they are subjective and the book is not a collaborative effort.

Last, feel free to send issues with the granularity you prefer, but if you can group things by type it would definitely help (e.g. typos).

Thanks again for reading the book.

**Comment by 1110sillabo** [comment]
Thanks for the reply. I really feel you on the "too much proofreading it kills you".
I guess I'll go by chapters using GitHub edits. (Spoiler: most of the things I've seen were at the earliest chapter. I guess my typokiller skills goes to zero as soon as things get less discursive :) )
It will be some kind of way to play along with your book and actually getting the things done after a first end-to-end reading. But before starting that I'll go finish homework and read your Flask, TDD, Docker, PostgreS series. (Your book and your blog are a gold mine - thanks!)

**Comment by lgiordani** [comment]
Thank you! The reason why typos are in the first chapters is because those are the ones I added in the second edition. The rest of the book has already been patiently proofread by other charitable readers like you 😹

**Comment by lgiordani** [comment]
This has been solved in version 2.1.0. Thanks!
